# Generated by Django 4.2.7 on 2023-11-20 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='org_id_name',
            new_name='org_name',
        ),
    ]
